# Generated by Django 4.1.7 on 2023-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livres',
            fields=[
                ('identifiant', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('date_publication', models.DateField()),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('identifiant', models.IntegerField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]

class Migrations(migrations.Migration):

    dependencies = [
        ('gres', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE User MODIFY COLUMN identifiant INT AUTO_INCREMENT'),
        migrations.RunSQL('ALTER TABLE Livres MODIFY COLUMN identifiant INT AUTO_INCREMENT'),
    ]