# Generated by Django 4.1.7 on 2023-03-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gres', '0002_alter_livres_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='identifiant',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Emprunts',
            fields=[
                ('identifiant', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gres.livres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gres.users')),
            ],
        ),
    ]
